version: '3'

services:
  web:
    build: .
    container_name: web
    tty: true
    volumes:
      - .:/var/app
    ports:
      - '8080:8080'
    environment:
      - VIRTUAL_HOST=ttm.web

  proxy:
    image: jwilder/nginx-proxy
    container_name: proxy
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
