name: Check commit
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Lint scripts
        run: yarn lint:scripts
      - name: Lint styles
        run: yarn lint:styles
      - name: Run tests
        run: yarn test
      - name: Deploy to Github Pages
        run: |
          git config user.name pgalias && git config user.email pawel@galias.me
          yarn deploy
