name: Check commit
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Lint scripts
        run: yarn lint:scripts
      - name: Lint styles
        run: yarn lint:styles
      - name: Run unit tests
        run: yarn test:unit
      - name: Run e2e tests
        if: github.ref == 'refs/heads/main'
        run: |
          yarn start
          yarn test:e2e
      - name: Deploy to Github Pages
        if: github.ref == 'refs/heads/main'
        run: |
          git config user.name pgalias && git config user.email pawel@galias.me
          yarn deploy
