name: Code Coverage

on:
  push:
    branches: [ main ]
    
jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Run tests
        run: yarn test:unit
      - name: Upload code coverage
        uses: codecov/codecov-action@v1
